#!/bin/bash

newClasspath=$CLASSPATH:../LilleWebMarket/WEB-INF/classes/:..LilleWebMarket/WEB-INF/libcommons-lang3-3.2.1.jar

echo "Beans compilation..."
rm -f ../LilleWebMarket/WEB-INF/classes/dao/*.class
javac -cp $newClasspath ../LilleWebMarket/WEB-INF/classes/dao/*.java
echo "done."

echo "Servlets compilation..."
rm -f ../LilleWebMarket/WEB-INF/classes/servlet/*.class
javac -cp $newClasspath ../LilleWebMarket/WEB-INF/classes/servlet/*.java
echo "done."
